const assert=require('node:assert/strict');
const {SG,DATA}=require('./load_node');SG.init(DATA);
require('../src/pvp_catalog');require('../src/engine_pvp');require('../src/saveio');
const names=Object.keys(SG.God.DATA);
const unit=(n,form='god')=>SG.mkHeroUnit(n,100,7,[],null,form);
const battle=(n,others=['刘备','赵云'])=>{const u=unit(n),A=[u,...others.filter(x=>x!==n).map(x=>unit(x,'normal'))],B=['曹操','夏侯惇','张辽'].map(x=>unit(x,'normal'));const b=new SG.Battle(A,B,true);b.round=1;return {u,A,B,b};};
let checks=0;function check(label,fn){fn();checks++;console.log('✓ '+label);}
check('四阵营各5位，属性先于装备且不加兵力',()=>{assert.equal(names.length,20);for(const f of ['魏','蜀','吴','汉'])assert.equal(names.filter(n=>SG.God.DATA[n].faction===f).length,5);for(const n of names){const a=unit(n),b=unit(n,'normal'),m=SG.God.DATA[n];for(const k in a.base)assert.equal(a.base[k],b.base[k]*(k===m.primary?1.08:k===m.secondary?1.04:1));assert.equal(a.maxhp,b.maxhp);}});
check('觉醒费用原子扣减，旧档普通，存档形态/培养/装备往返',()=>{const g=SG.Game.fresh(88);g.s.cycle=2;g.addHero('张飞');const h=g.hero('张飞');Object.assign(h,{lv:70,star:5,frag:11,exp:99,hp:70000});const p=g.godProgress('张飞');Object.assign(p,{qualified:true,souls:0});g.s.gold=999999;assert.ok(g.awaken('张飞').err);assert.equal(g.s.gold,999999);g.s.gold=1000000;assert.ok(g.awaken('张飞').ok);assert.equal(p.souls,0);assert.equal(g.s.gold,0);assert.ok(g.setGodForm('张飞','god').ok);const clone=SG.Game.load(g.toJSON());assert.deepEqual(clone.hero('张飞'),h);assert.ok(clone.godProgress('张飞').awakened);assert.equal(clone.unitOf('张飞').form,'god');clone.setGodForm('张飞','normal');assert.equal(clone.hero('张飞').frag,11);delete g.s.gods;delete h.form;assert.notEqual(SG.Game.load(g.toJSON()).unitOf('张飞').form,'god');});
check('所有神技执行、完整战斗无NaN或无限连锁；四件套不换回本体技',()=>{for(const n of names){for(let seed=0;seed<15;seed++){SG.setBattleSeed(seed);const {u,A,B,b}=battle(n);u.skill.fn(b,u,B[0]);b.run(12);for(const x of [...A,...B])assert.ok(Number.isFinite(x.hp)&&Number.isFinite(x.stat('atk')),n);}const ids=(SG.D.EXCL[n]||[]).map(x=>x.id);const u=SG.mkHeroUnit(n,70,5,ids,null,'god');assert.ok(u.skill.god,n);assert.ok(u.extras.every(x=>!x.name.includes('四件')||x.name==='四件'));}});
check('双方一神将限制（底层统一覆盖所有战斗）',()=>{assert.throws(()=>new SG.Battle([unit('张飞'),unit('关羽')],[unit('吕布')]),/最多/);assert.throws(()=>new SG.Battle([unit('张飞')],[unit('吕布'),unit('貂蝉')]),/最多/);});
check('净化一次一控制、禁疗和免控生效',()=>{const {u,B,b}=battle('刘备');u.status={'计穷':2,'缴械':2};assert.ok(SG.God.cleanse(u));assert.equal(Object.keys(u.status).length,1);u.hp=100;u.status['禁疗']=2;b.heal(u,u,.5);assert.equal(u.hp,100);b.hooks.push(['resist_status',B[0],()=>true]);assert.equal(B[0].add_status('震慑',1,1,u),false);});
check('典韦免死一次，替受上限及群攻/持续伤害排除',()=>{const {u,A,B,b}=battle('典韦');b.apply(B[0],u,200000,'phys','attack');assert.equal(u.hp,15000);b.apply(B[0],u,200000,'phys','attack');assert.equal(u.hp,0);const q=battle('典韦'),t=q.A[1];t.hp=1;q.u.flags.godDianStop=0;SG.setBattleSeed(5);for(let i=0;i<100;i++)q.b.hook_all('substitute',t,q.B[0],'phys','attack');assert.equal(q.u.flags.godDianSub1,2);q.b.round=2;q.b.godContext={aoe:true};assert.equal(q.b.hook_all('substitute',t,q.B[0],'phys','skill'),null);q.b.godContext={};assert.equal(q.b.hook_all('substitute',t,q.B[0],'mag','灼烧'),null);});
check('赵云行动前解控，但该回合追击禁用；张飞反击每回合一次且不递归',()=>{const {u,B,b}=battle('赵云');u.status['震慑']=1;b.hook_all('before_action',u);assert.ok(!u.has('震慑'));const hp=B[0].hp;u.skill.fn(b,u,B[0]);assert.equal(B[0].hp,hp);const q=battle('张飞');q.b.godContext={active:true};SG.setBattleSeed(44);q.b.hook_all('on_hit_taken',q.u,q.B[0],100,'phys','skill');const v=q.B[0].hp;q.b.hook_all('on_hit_taken',q.u,q.B[0],100,'phys','skill');assert.equal(q.B[0].hp,v);});
check('准备型神技可打断，陆逊消耗灼烧，周瑜不叠层',()=>{for(const n of ['诸葛亮','陆逊','张角']){const {u,B,b}=battle(n);u.prep=u.skill.fn;SG.setBattleSeed(1);assert.ok(u.add_status('计穷',1,1,B[0]));assert.equal(u.prep,null);}const q=battle('陆逊');q.B.forEach(t=>t.status['灼烧']=2);q.u.skill.fn(q.b,q.u);q.B.forEach(t=>assert.ok(!t.has('灼烧')));const z=battle('周瑜');z.u.skill.fn(z.b,z.u);z.u.skill.fn(z.b,z.u);z.B.forEach(t=>assert.ok((t.status['灼烧']||0)<=2));});
check('郭嘉遗策与免死复活不重置，司马懿/关羽/张角层数封顶死亡清零',()=>{const q=battle('郭嘉');q.b.hook_all('on_death',q.u,q.B[0]);q.A[1].flags.godNextRate=0;q.b.hook_all('on_death',q.u,q.B[0]);assert.equal(q.A[1].flags.godNextRate,0);for(const [n,ev,k,max] of [['司马懿','round_end_unit','godSima',5],['关羽','on_kill','godGuan',3]]){const {u,b,B}=battle(n);for(let i=0;i<20;i++)b.hook_all(ev,u,B[0]);assert.equal(u.flags[k],max);b.hook_all('on_death',u,B[0]);assert.ok(!u.flags[k]);}const {u,b,B}=battle('张角');for(let i=0;i<20;i++)u.skill.fn(b,u,B[0]);assert.equal(u.flags.godJiao,3);b.hook_all('on_death',u,B[0]);assert.ok(!u.flags.godJiao);});
check('试炼通过取得资格，重复挑战不增加资源，失败不扣资源',()=>{const g=SG.Game.fresh(90);g.s.cycle=2;names.slice(0,9).forEach(n=>{g.addHero(n);Object.assign(g.hero(n),{lv:100,star:7,hp:100000});});g.s.formation=names.slice(0,9);const before=JSON.stringify(g.s.heroes),gold=g.s.gold;let out=g.godTrial('典韦',g.s.formation,{seed:3,quick:true});assert.ok(out.res.win);assert.ok(g.godProgress('典韦').qualified);assert.ok(!out.note.includes('神魂'));g.godTrial('典韦',g.s.formation,{seed:3,quick:true});assert.equal(g.s.gold,gold);assert.equal(JSON.stringify(g.s.heroes),before);g.hero('典韦').lv=70;out=g.godTrial('典韦',['典韦',...Array(8).fill(null)],{seed:3,quick:true});assert.ok(!out.res.win);assert.equal(g.s.gold,gold);});
check('刘备护盾最多两人一次、曹操/孙权阵亡效果一次、袁绍击杀每回合一次',()=>{
 const q=battle('刘备',['关羽','赵云','张飞']);q.A.forEach(t=>t.hp=20000);for(const t of q.A){q.b.hook_all('on_damage_any',t,q.B[0]);q.b.hook_all('on_damage_any',t,q.B[0]);}assert.equal(q.A.filter(t=>t.shield>0).length,2);
 for(const n of ['曹操','孙权']){const {u,A,b}=battle(n);b.hook_all('on_ally_death',u,A[1]);A.forEach(t=>{t.shield=0;t.buffs=[];});b.hook_all('on_ally_death',u,A[1]);assert.ok(A.every(t=>t.shield===0&&t.buffs.length===0));}
 const z=battle('袁绍',['吕布','貂蝉']);z.A[1].hp=10000;z.b.hook_all('kill_any',z.A[1],z.B[0]);assert.equal(z.A[1].hp,15000);z.b.hook_all('kill_any',z.A[1],z.B[0]);assert.equal(z.A[1].hp,15000);
});
check('甘宁首杀恢复一次、孙策本次暴击不泄漏、陆逊准备盾与華佗周期治疗',()=>{
 const q=battle('甘宁');q.u.hp=10000;q.b.hook_all('on_kill',q.u,q.B[0]);assert.equal(q.u.hp,16000);q.b.hook_all('on_kill',q.u,q.B[0]);assert.equal(q.u.hp,16000);
 const z=battle('孙策');z.u.flags.crit=.1;z.u.skill.fn(z.b,z.u,z.B[0]);assert.equal(z.u.flags.crit,.1);
 const l=battle('陆逊');l.b.hook_all('on_prepare',l.u,l.u);assert.equal(l.u.shield,8000);l.u.shield=0;l.b.hook_all('on_prepare',l.u,l.u);assert.equal(l.u.shield,0);
 const h=battle('华佗');h.A.forEach(t=>t.hp=10000);h.b.round=2;h.b.hook_all('round_end_unit',h.u);assert.equal(h.u.hp,10000);h.b.round=3;h.b.hook_all('round_end_unit',h.u);assert.equal(h.u.hp,13000);
});
check('跨周目保留觉醒与神魂、神形态也受100级七星上限',()=>{const g=SG.Game.fresh(93);g.s.cycle=2;g.addHero('张飞');Object.assign(g.hero('张飞'),{lv:100,star:7,form:'god'});Object.assign(g.godProgress('张飞'),{qualified:true,awakened:true,souls:150});const last=SG.D.STAGES.find(x=>x['章']==='26'&&x['类型']==='章末');g.s.cleared[last.id]=true;assert.ok(g.newCycle());assert.equal(g.s.cycle,3);assert.equal(g.godProgress('张飞').souls,150);assert.equal(g.hero('张飞').form,'god');assert.equal(g.maxLv(),100);assert.equal(g.maxStar(),7);});
(async()=>{const g=SG.Game.fresh(91);const nine=['关羽','张飞','赵云','马超','黄忠','诸葛亮','刘备','曹操','孙权'];nine.forEach(n=>{g.addHero(n);Object.assign(g.hero(n),{lv:70,star:5});});const p=SG.PVP.state(g);p.name='神将测试';p.cells=nine;g.hero('张飞').form='god';const s=SG.PVP.snapshot(g);assert.equal(s.team[1].form,'god');const code=SG.PVP.encode(s);assert.ok(code.startsWith('SGP3:'));assert.deepEqual(SG.PVP.decode(code),s);const normal=structuredClone(s);delete normal.team[1].form;assert.notEqual(SG.PVP.identity(s),SG.PVP.identity(normal));s.team[0].form='god';assert.throws(()=>SG.PVP.validate(s),/最多/);console.log(`✓ PVP 神将形态进码、与普通形态奖励身份分离；${checks+1}组验收通过`);})().catch(e=>{console.error(e);process.exitCode=1;});
